version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests with coverage
          command: npm run test
      - run:
          name: Upload coverage data
          command: bash <(curl -s https://codecov.io/bash)
