name: Node.js Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-node:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript files
        run: npm run build

      - name: Run the application
        run: npx nodemon 
